//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var Bookmarks = newBookmarksTable("public", "bookmarks", "")

type bookmarksTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnString
	UserID    postgres.ColumnString
	TargetID  postgres.ColumnString
	Title     postgres.ColumnString
	Query     postgres.ColumnString
	CreatedAt postgres.ColumnTimestampz

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type BookmarksTable struct {
	bookmarksTable

	EXCLUDED bookmarksTable
}

// AS creates new BookmarksTable with assigned alias
func (a BookmarksTable) AS(alias string) *BookmarksTable {
	return newBookmarksTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new BookmarksTable with assigned schema name
func (a BookmarksTable) FromSchema(schemaName string) *BookmarksTable {
	return newBookmarksTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new BookmarksTable with assigned table prefix
func (a BookmarksTable) WithPrefix(prefix string) *BookmarksTable {
	return newBookmarksTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new BookmarksTable with assigned table suffix
func (a BookmarksTable) WithSuffix(suffix string) *BookmarksTable {
	return newBookmarksTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newBookmarksTable(schemaName, tableName, alias string) *BookmarksTable {
	return &BookmarksTable{
		bookmarksTable: newBookmarksTableImpl(schemaName, tableName, alias),
		EXCLUDED:       newBookmarksTableImpl("", "excluded", ""),
	}
}

func newBookmarksTableImpl(schemaName, tableName, alias string) bookmarksTable {
	var (
		IDColumn        = postgres.StringColumn("id")
		UserIDColumn    = postgres.StringColumn("user_id")
		TargetIDColumn  = postgres.StringColumn("target_id")
		TitleColumn     = postgres.StringColumn("title")
		QueryColumn     = postgres.StringColumn("query")
		CreatedAtColumn = postgres.TimestampzColumn("created_at")
		allColumns      = postgres.ColumnList{IDColumn, UserIDColumn, TargetIDColumn, TitleColumn, QueryColumn, CreatedAtColumn}
		mutableColumns  = postgres.ColumnList{UserIDColumn, TargetIDColumn, TitleColumn, QueryColumn, CreatedAtColumn}
		defaultColumns  = postgres.ColumnList{}
	)

	return bookmarksTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		UserID:    UserIDColumn,
		TargetID:  TargetIDColumn,
		Title:     TitleColumn,
		Query:     QueryColumn,
		CreatedAt: CreatedAtColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
