//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/postgres"
)

var GooseMigrations = newGooseMigrationsTable("public", "goose_migrations", "")

type gooseMigrationsTable struct {
	postgres.Table

	// Columns
	ID        postgres.ColumnInteger
	VersionID postgres.ColumnInteger
	IsApplied postgres.ColumnBool
	Tstamp    postgres.ColumnTimestamp

	AllColumns     postgres.ColumnList
	MutableColumns postgres.ColumnList
	DefaultColumns postgres.ColumnList
}

type GooseMigrationsTable struct {
	gooseMigrationsTable

	EXCLUDED gooseMigrationsTable
}

// AS creates new GooseMigrationsTable with assigned alias
func (a GooseMigrationsTable) AS(alias string) *GooseMigrationsTable {
	return newGooseMigrationsTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new GooseMigrationsTable with assigned schema name
func (a GooseMigrationsTable) FromSchema(schemaName string) *GooseMigrationsTable {
	return newGooseMigrationsTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new GooseMigrationsTable with assigned table prefix
func (a GooseMigrationsTable) WithPrefix(prefix string) *GooseMigrationsTable {
	return newGooseMigrationsTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new GooseMigrationsTable with assigned table suffix
func (a GooseMigrationsTable) WithSuffix(suffix string) *GooseMigrationsTable {
	return newGooseMigrationsTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newGooseMigrationsTable(schemaName, tableName, alias string) *GooseMigrationsTable {
	return &GooseMigrationsTable{
		gooseMigrationsTable: newGooseMigrationsTableImpl(schemaName, tableName, alias),
		EXCLUDED:             newGooseMigrationsTableImpl("", "excluded", ""),
	}
}

func newGooseMigrationsTableImpl(schemaName, tableName, alias string) gooseMigrationsTable {
	var (
		IDColumn        = postgres.IntegerColumn("id")
		VersionIDColumn = postgres.IntegerColumn("version_id")
		IsAppliedColumn = postgres.BoolColumn("is_applied")
		TstampColumn    = postgres.TimestampColumn("tstamp")
		allColumns      = postgres.ColumnList{IDColumn, VersionIDColumn, IsAppliedColumn, TstampColumn}
		mutableColumns  = postgres.ColumnList{VersionIDColumn, IsAppliedColumn, TstampColumn}
		defaultColumns  = postgres.ColumnList{TstampColumn}
	)

	return gooseMigrationsTable{
		Table: postgres.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:        IDColumn,
		VersionID: VersionIDColumn,
		IsApplied: IsAppliedColumn,
		Tstamp:    TstampColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
		DefaultColumns: defaultColumns,
	}
}
