# Database Gateway provides access to servers with ACL for safe and restricted database interactions.
# Copyright (C) 2024  Kirill Zhuravlev
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

services:
  dex:
    image: bitnami/dex
    ports:
      - '127.0.0.1:5556:5556'
    volumes:
      - './dex-config.yaml:/etc/dex/config.yaml'
    command: [ 'serve', '/etc/dex/config.yaml' ]

  # This is a primary application storage
  storage-postgres:
    image: postgres:16
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_DB: local__dbgw
      POSTGRES_USER: local__dbgw
      POSTGRES_PASSWORD: local__dbgw

  # This is an external databases

  postgres-5433:
    image: postgres:16
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      POSTGRES_DB: pg5433
      POSTGRES_USER: pg5433
      POSTGRES_PASSWORD: pg5433
    volumes:
      - './init-5433.sql:/docker-entrypoint-initdb.d/init.sql'

  postgres-5434:
    image: postgres:16
    ports:
      - '127.0.0.1:5434:5432'
    environment:
      POSTGRES_DB: pg5434
      POSTGRES_USER: pg5434
      POSTGRES_PASSWORD: pg5434
    volumes:
      - './init-5434.sql:/docker-entrypoint-initdb.d/init.sql'

  postgres-5435:
    image: postgres:16
    ports:
      - '127.0.0.1:5435:5432'
    environment:
      POSTGRES_DB: pg5435
      POSTGRES_USER: pg5435
      POSTGRES_PASSWORD: pg5435
    volumes:
      - './init-5435.sql:/docker-entrypoint-initdb.d/init.sql'
