services:
  postgres-1:
    image: postgres:16
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_DB: pg01
      POSTGRES_USER: pg01
      POSTGRES_PASSWORD: pg01
    volumes:
      - './init-01.sql:/docker-entrypoint-initdb.d/init.sql'

  postgres-2:
    image: postgres:16
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      POSTGRES_DB: pg02
      POSTGRES_USER: pg02
      POSTGRES_PASSWORD: pg02
    volumes:
      - './init-02.sql:/docker-entrypoint-initdb.d/init.sql'

  postgres-3:
    image: postgres:16
    ports:
      - '127.0.0.1:5434:5432'
    environment:
      POSTGRES_DB: pg03
      POSTGRES_USER: pg03
      POSTGRES_PASSWORD: pg03
    volumes:
      - './init-03.sql:/docker-entrypoint-initdb.d/init.sql'
