services:
  postgres-1:
    image: postgres:16
    ports:
      - '127.0.0.1:5432:5432'
    environment:
      POSTGRES_DB: local_dbgw
      POSTGRES_USER: local_dbgw
      POSTGRES_PASSWORD: local_dbgw

  postgres-2:
    image: postgres:16
    ports:
      - '127.0.0.1:5433:5432'
    environment:
      POSTGRES_DB: local_sample
      POSTGRES_USER: local_sample
      POSTGRES_PASSWORD: local_sample

  postgres-3:
    image: postgres:16
    ports:
      - '127.0.0.1:5434:5432'
    environment:
      POSTGRES_DB: local_example
      POSTGRES_USER: local_example
      POSTGRES_PASSWORD: local_example
