before:
  hooks:
    - go mod tidy

builds:
  - id: 'database-gateway'
    binary: 'database-gateway'
    main: ./cmd/gateway
    ldflags:
      - -s
      - -w
      - -X main.version={{.Summary}}
    mod_timestamp: '{{ .CommitTimestamp }}'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
#    goarm:
#      - 6
#      - 7
#    goamd64:
#      - v2
#      - v3
#    goarm64:
#      - v9.0
dockers:
  - id: 'database-gateway'
    goos: linux
    goarch: amd64
    ids:
      - 'database-gateway'
    image_templates:
      - "kazhuravlev/database-gateway:latest"
      - "kazhuravlev/database-gateway:{{ .Tag }}"
      - "kazhuravlev/database-gateway:v{{ .Major }}"
      - "kazhuravlev/database-gateway:v{{ .Major }}.{{ .Minor }}"
    dockerfile: 'Dockerfile'
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
brews:
  - name: 'database-gateway'
    goarm: "6"
    goamd64: v3
    repository:
      owner: 'kazhuravlev'
      name: 'homebrew-database-gateway'
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    url_template: "https://github.com/kazhuravlev/database-gateway/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: goreleaserbot
      email: kazhuravlev+goreleaserbot@fastmail.com
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    homepage: "https://github.com/kazhuravlev/database-gateway"
    description: "Safe access to production databases"
    license: "GPL-3.0"
    test: |
      system "#{bin}/gateway help"
archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
