// Code generated by options-gen v0.49.0. DO NOT EDIT.

package facade

import (
	fmt461e464ebed9 "fmt"
	"log/slog"

	"github.com/kazhuravlev/database-gateway/internal/app"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger *slog.Logger,
	app *app.Service,
	cookieSecret string,
	port int,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.logger = logger
	o.app = app
	o.cookieSecret = cookieSecret
	o.port = port

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("app", _validate_Options_app(o)))
	errs.Add(errors461e464ebed9.NewValidationError("cookieSecret", _validate_Options_cookieSecret(o)))
	errs.Add(errors461e464ebed9.NewValidationError("port", _validate_Options_port(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_app(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.app, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `app` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_cookieSecret(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.cookieSecret, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `cookieSecret` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_port(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.port, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `port` did not pass the test: %w", err)
	}
	return nil
}
